/**
 * @file tkl_cellular_gnss.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 *
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 *
 */

// --- BEGIN: user defines and implements ---
#include "tkl_cellular_gnss.h"
#include "tuya_error_code.h"

#if !defined(ENABLE_CELLULAR_PLUGIN) || ENABLE_CELLULAR_PLUGIN == 0
#if defined(ENABLE_CELLULAR_GPS_INSIDE) && ENABLE_CELLULAR_GPS_INSIDE == 1
// --- END: user defines and implements ---

/**
 * @brief 初始化蜂窝GNSS服务
 * @param handle 返回蜂窝GNSS设备服务句柄
 * @return 0 成功  其它 失败
 */
OPERATE_RET tkl_cellular_gnss_init(TUYA_CELLULAR_GNSS_DEV_HANDLE *handle)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief 去初始化蜂窝GNSS服务
 * @param handle 蜂窝GNSS设备服务句柄
 * @return 0 成功  其它 失败
 */
OPERATE_RET tkl_cellular_gnss_deinit(TUYA_CELLULAR_GNSS_DEV_HANDLE handle)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief 注册蜂窝GNSS服务消息回调函数
 * @param notify TKL_GNSS_REGISTION_NOTIFY 回调函数
 * @return 0 成功  其它 失败
 */
OPERATE_RET tkl_cellular_gnss_register_notify(TKL_GNSS_REGISTION_NOTIFY notify)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief 设置蜂窝GNSS定位模式
 * @param handle 蜂窝GNSS设备服务句柄
 * @param pt_mode 定位模式
 * @return 0 成功  其它 失败
 */
OPERATE_RET tkl_cellular_gnss_set_position_mode(TUYA_CELLULAR_GNSS_DEV_HANDLE nohandletify, TUYA_CELLULAR_GNSS_MODE_INFO_T pt_mode)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief 设置蜂窝GNSS定位系统模式
 * @param handle 蜂窝GNSS设备服务句柄
 * @param pt_mode 定位模式
 * @return 0 成功  其它 失败
 */
OPERATE_RET tkl_cellular_gnss_set_system_mode(TUYA_CELLULAR_GNSS_DEV_HANDLE nohandletify, TUYA_CELLULAR_GNSS_SYS_MODE_E pt_mode)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief 启动导航
 * @param handle 蜂窝GNSS设备服务句柄
 * @return 0 成功  其它 失败
 */
OPERATE_RET tkl_cellular_gnss_start_navigation(TUYA_CELLULAR_GNSS_DEV_HANDLE handle)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief 停止导航
 * @param handle 蜂窝GNSS设备服务句柄
 * @return 0 成功  其它 失败
 */
OPERATE_RET tkl_cellular_gnss_stop_navigation(TUYA_CELLULAR_GNSS_DEV_HANDLE handle)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief 获取当前的位置信息
 * @param handle 蜂窝GNSS设备服务句柄
 * @param location  位置信息
 * @param timeout_sec 获取位置信息的超时时间
 * @return 0 成功  其它 失败
 */
OPERATE_RET tkl_cellular_gnss_get_location(TUYA_CELLULAR_GNSS_DEV_HANDLE handle,TUYA_CELLULAR_GNSS_LOCATION_INFO_T *location,int timeout_sec)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief 直接注入时间数据
 * @param handle 蜂窝GNSS设备服务句柄
 * @param pt_info  时间数据
 * @return 0 成功  其它 失败
 */
OPERATE_RET tkl_cellular_gnss_injecttime(TUYA_CELLULAR_GNSS_DEV_HANDLE handle,TUYA_CELLULAR_GNSS_INJECT_TIME_INFO_T *pt_info)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief 直接注入位置信息
 * @param handle 蜂窝GNSS设备服务句柄
 * @param pt_info  位置数据
 * @return 0 成功  其它 失败
 */
OPERATE_RET tkl_cellular_gnss_injectlocation(TUYA_CELLULAR_GNSS_DEV_HANDLE handle, TUYA_CELLULAR_GNSS_INJECT_LOCATION_INFO_T *pt_info)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief GNSS服务的自定义接口
 * @param handle 蜂窝GNSS设备服务句柄
 * @param cmd  GNSS命令
 * @param pdata 数据指针
 * @param datalen pdata size
 * @return 0 成功  其它 失败
 */
OPERATE_RET tkl_cellular_gnss_ioctl(TUYA_CELLULAR_GNSS_DEV_HANDLE handle,int cmd,void *pdata,int datalen)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

// --- BEGIN: user defines and implements ---
#endif
#endif
// --- END: user defines and implements ---
