/**
 * @file tkl_wired.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 *
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 *
 */

// --- BEGIN: user defines and implements ---
#include "tuya_error_code.h"
#include "tuya_cloud_types.h"
#if defined(ENABLE_WIRED) && (ENABLE_WIRED == 1)
#include "tkl_output.h"
#include "tkl_wired.h"

TKL_WIRED_STATUS_CHANGE_CB wired_status_cb = NULL;
static TKL_WIRED_STAT_E wired_status = TKL_WIRED_LINK_DOWN;

#define LOGD(fmt, ...)  tkl_log_output("[tkl_wired][DBG/%d]: " fmt "\r\n", __LINE__, ##__VA_ARGS__)

OPERATE_RET tkl_wired_set_status(TKL_WIRED_STAT_E status)
{
    // --- BEGIN: user implements ---
    LOGD("set wired_status = %d", status);
    wired_status = status;
    if(wired_status_cb) {
        wired_status_cb(status);
    }
    return OPRT_OK;
    // --- END: user implements ---
}

/**
 * @brief  set the ip address of the wired link
 *
 * @param[in]   ip: the ip address
 *
 * @return OPRT_OK on success. Others on error, please refer to
 * tuya_error_code.h
 */
OPERATE_RET tkl_wired_set_ip(NW_IP_S *ip)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

// --- END: user defines and implements ---

/**
 * @brief  get the link status of wired link
 *
 * @param[out]  is_up: the wired link status is up or not
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_wired_get_status(TKL_WIRED_STAT_E *status)
{
    // --- BEGIN: user implements ---
    *status = wired_status;
    return OPRT_OK;
    // --- END: user implements ---
}

/**
 * @brief  set the status change callback
 *
 * @param[in]   cb: the callback when link status changed
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_wired_set_status_cb(TKL_WIRED_STATUS_CHANGE_CB cb)
{
    // --- BEGIN: user implements ---
    wired_status_cb = cb;
    return OPRT_OK;
    // --- END: user implements ---
}

/**
 * @brief  get the ip address of the wired link
 *
 * @param[in]   ip: the ip address
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_wired_get_ip(NW_IP_S *ip)
{
    // --- BEGIN: user implements ---
    extern OPERATE_RET tkl_cellular_mds_get_ip(uint8_t sim_id,NW_IP_S *ip);
    return tkl_cellular_mds_get_ip(0,ip);
    // --- END: user implements ---
}

/**
 * @brief  get the ip address of the wired link
 *
 * @param[in]   ip: the ip address
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_wired_get_ipv6(NW_IP_TYPE type, NW_IP_S *ip)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief  get the mac address of the wired link
 *
 * @param[in]   mac: the mac address
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_wired_get_mac(NW_MAC_S *mac)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief  set the mac address of the wired link
 *
 * @param[in]   mac: the mac address
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_wired_set_mac(const NW_MAC_S *mac)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}
// --- BEGIN: user defines and implements ---
#endif
// --- END: user defines and implements ---
