#if !defined _DB_VERSION_H 
#define _DB_VERSION_H

//The file was automatically generated by the PrePass Application Ver 2.2.77.207, Tue Aug 19 19:51:52 2025

#define DB_VERSION_UNIQ_ID "0x6ff69fc1"

#endif //_DB_VERSION_H
