#if !defined _DB_VERSION_H 
#define _DB_VERSION_H

//The file was automatically generated by the PrePass Application Ver 2.2.77.207, Thu Aug 14 09:18:20 2025

#define DB_VERSION_UNIQ_ID "0xdc9e3e9a"

#endif //_DB_VERSION_H
