#if !defined _DB_VERSION_H 
#define _DB_VERSION_H

//The file was automatically generated by the PrePass Application Ver 2.2.77.207, Thu Aug 14 19:00:32 2025

#define DB_VERSION_UNIQ_ID "0x79bc5521"

#endif //_DB_VERSION_H
